#!/usr/bin/env bash
#Bash script that transfers a file from our client to a server

if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

file_path="$1"
server_ip="$2"
ubuntu="$3"
ssh_key_path="$4"

# Display information about the transfer
echo "Transferring file $file_path to $ubuntu@$server_ip:~/"

# Use scp to transfer the file with strict host key checking disabled
scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "$ubuntu@$server_ip":~/

# Check if the transfer was successful
if [ "$?" -eq 0 ]; then
    echo "File transfer completed successfully."
else
    echo "File transfer failed."
fi