#!/usr/bin/env bash
#Bash script that transfers a file from our client to a server

if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

file_path ="$1"
54.84.205.150 ="$2"
ubuntu ="$3"
54.84.205.150 ="$4"

# Display information about the transfer
echo "Transferring file $file_path to $username@$server_ip:~/"

# Use scp to transfer the file with strict host key checking disabled
scp -o StrictHostKeyChecking=no -i "$54.84.205.150" "$file_path" "183186-web-01":~/

# Check if the transfer was successful
if [ "$?" -eq 0 ]; then
    echo "File transfer completed successfully."
else
    echo "File transfer failed."
fi