#!/usr/bin/env bash
# write a Bash script that configures a new Ubuntu machine to respect above requirements (this script will be run on the server itself

# Step 1: Update the package list
sudo apt update

# Step 2: Install Nginx
sudo apt -y install nginx

# Step 3: Change ownership of HTML files in /var/www/html/
sudo chown -R "$USER":"$USER" /var/www/html/*.html

# Step 4: Write "Hello World!" to HTML files in /var/www/html/
echo "Hello World!" > /var/www/html/*.html

# Step 5: Start the Nginx service
sudo service nginx start

# Step 6: Reload Nginx to apply changes
sudo ngink -s reload

# Step 7: Use curl to make a request to the Nginx server running on localhost
sudo curl localhost