#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page

# Step 1: Update the package list
sudo apt-get update

# Step 2: Install Nginx
sudo apt-get install -y nginx

# Step 3: Create and move the default index.html
echo "Hello World!" > index.html
sudo mv index.html /var/www/html

# Step 4: Create and move the 404.html
echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html

# Step 5: Define Nginx server configuration in a file named 'default'
echo "server {
   listen 80 default_server;
   listen [::]:80 default_server;
   
   root /var/www/html;
   index index.html;
   
   # Redirect specific URL to YouTube
   location /redirect_me {
      return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
   }

   # Configure custom 404 error page
   error_page 404 /404.html;
   location = /404.html {
      internal;
   }
}" > default

# Step 6: Move the 'default' configuration file to Nginx sites-available directory
sudo mv -f default /etc/nginx/sites-available/default

# Step 7: Restart Nginx to apply changes
sudo service nginx restart
