#!/usr/bin/env bash
# configure a load-balancing server

# Install HAProxy
sudo apt-get install -y --no-install-recommends software-properties-common
sudo apt-get update -y
sudo apt-get install -y haproxy

# Configure HAProxy
sudo sed -i 's/^\(ENABLED=\).*/\11/' /etc/default/haproxy

# Create a new HAProxy configuration file
echo \
	"
frontend davidking.tech
	bind *:80
	mode http
	default_backend davidking.tech
backend davidking.tech
	mode http
	balance roundrobin
	server 292197-web-01 18.215.160.57
	server 292197-web-02 3.80.18.18" >> /etc/haproxy/haproxy.cfg

# Restart HAProxy service
sudo service haproxy restart
