#!/usr/bin/env bash
# configure a load-balancing server

# Install HAProxy
sudo apt-get install -y --no-install-recommends software-properties-common
sudo apt-get update -y
sudo apt-get install -y haproxy

# Configure HAProxy
sudo sed -i 's/^\(ENABLED=\).*/\11/' /etc/default/haproxy

# Create a new HAProxy configuration file
echo \
	"
frontend realzy.tech
	bind *:80
	mode http
	default_backend realzy.tech
backend realzy.tech
	mode http
	balance roundrobin
	server 183186-web-01 54.84.205.150
	server 183186-web-02 52.91.131.132 >> /etc/haproxy/haproxy.cfg

# Restart HAProxy service
sudo service haproxy restart
