#!/usr/bin/env bash
# configure a load-balancing server

STUDENT_ID="183186"
WEB_SERVER_1="54.84.205.150"
WEB_SERVER_2="52.91.131.132"

# Update the package list
sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOL
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend main
    bind *:80
    default_backend app

backend app
    balance roundrobin
    server web-01 ${183186}-web-01:${54.84.205.150} check
    server web-02 ${183186}-web-02:${52.91.131.132} check
EOL

# Ensure HAProxy can be managed via an init script
sudo systemctl enable haproxy
sudo systemctl restart haproxy

# Display a message indicating successful configuration
echo "HAProxy has been installed and configured successfully. Web servers: ["web-01", "web-02"]"


# # Install HAProxy
# sudo apt-get install -y --no-install-recommends software-properties-common
# sudo apt-get update -y
# sudo apt-get install -y haproxy

# # Configure HAProxy
# sudo sed -i 's/^\(ENABLED=\).*/\11/' /etc/default/haproxy

# # Create a new HAProxy configuration file
# echo \
# 	"
# frontend realzy.tech
# 	bind *:80
# 	mode http
# 	default_backend realzy.tech
# backend realzy.tech
# 	mode http
# 	balance roundrobin
# 	server 183186-web-01 54.84.205.150
# 	server 183186-web-02 52.91.131.132 >> /etc/haproxy/haproxy.cfg

# # Restart HAProxy service
# sudo service haproxy restart
