#!/usr/bin/env bash
#script to ensure Nginx is running and listening on port 80
# How to solve?
# Deleting the existing ../sites-enabled/default and replacing it with a copy of
# ../sites-available/default. It can be done by creating a symbolic link.
# Note: The -s flag creates a symbolic link, -f deletes the existing file and replaces it.
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
