#!/usr/bin/env bash
#script to ensure Nginx is running and listening on port 80
# Note: The -s flag creates a symbolic link, -f deletes the existing file and replaces it.
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
