#!/usr/bin/env bash
# this script will display "Best School" 10 times using a while loop
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration

i=0;

while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck";
	elif [ $i -eq 7 ]
	then
		echo "good luck";
	else
		echo "Best School";
	fi
	(( i++ ));
done